/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IscrizioneLazyImport = createFileRoute('/iscrizione')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IscrizioneLazyRoute = IscrizioneLazyImport.update({
  path: '/iscrizione',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/iscrizione.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/iscrizione': {
      id: '/iscrizione'
      path: '/iscrizione'
      fullPath: '/iscrizione'
      preLoaderRoute: typeof IscrizioneLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  IscrizioneLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/iscrizione"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/iscrizione": {
      "filePath": "iscrizione.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
